server:
  port: 8088
spring:
  main:
    banner-mode: off
  application:
    name: gateway # 服务名称
  cloud:
    gateway:
      httpclient:
        pool:
          max-idle-time:
      filter:
        retry:
          enabled: true # 是否启用重试过滤器
          interval: 3 # 重试间隔时间(单位:秒)
          retries: 3 # 最大重试次数
      routes:
        - id: basic
          uri: lb://basic
          predicates:
            - Path=/basic/**
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**
        - id: websocket
          uri: lb://websocket
          predicates:
            - Path=/websocket/**
        - id: websocket-ws
          uri: lb:ws://websocket
          predicates:
            - Path=/websocket/**