server:
  port: 8805
spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  application:
    name: app
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.12:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 2762581@com